"""
backend/app/api/reports.py
Compliance Report generation endpoints for printable and downloadable verification dossiers.
Marked as 'AI-Assisted Verification Report'.
"""

import json
from datetime import datetime, timezone
from fastapi import APIRouter, Depends, HTTPException, Response
from fastapi.responses import HTMLResponse
from sqlalchemy.orm import Session
from app.db.session import get_db
from app.db.models import Tender, Bidder, VerificationResult, OfficerDecision, AuditLog
from app.services.verification_service import run_bidder_verification

router = APIRouter(prefix="/reports", tags=["Reports"])

@router.get("/{tender_id}/{bidder_id}")
def get_report_data(
    tender_id: str,
    bidder_id: str,
    db: Session = Depends(get_db)
):
    tender = db.query(Tender).filter(Tender.tender_id == tender_id).first()
    if not tender:
        raise HTTPException(status_code=404, detail="Tender not found")

    bidder = db.query(Bidder).filter(Bidder.bidder_id == bidder_id).first()
    if not bidder:
        raise HTTPException(status_code=404, detail="Bidder not found")

    ver = db.query(VerificationResult).filter(
        VerificationResult.tender_id == tender_id,
        VerificationResult.bidder_id == bidder_id
    ).order_by(VerificationResult.verified_at.desc()).first()

    if not ver:
        ver_data = run_bidder_verification(db, tender_id, bidder_id)
    else:
        ver_data = {
            "compliance_score": ver.compliance_score,
            "risk_level": ver.risk_level,
            "score_breakdown": {
                "total_score": ver.compliance_score,
                "statutory": ver.statutory_score,
                "tender_specific": ver.tender_score,
                "document_verification": ver.document_score,
                "govt_verification": ver.govt_score
            },
            "findings": json.loads(ver.findings_json) if ver.findings_json else [],
            "risk_factors": json.loads(ver.risk_factors_json) if ver.risk_factors_json else [],
            "requirement_results": json.loads(ver.rule_results_json) if ver.rule_results_json else [],
            "ai_recommendation": ver.ai_recommendation,
            "verified_at": ver.verified_at.isoformat() if ver.verified_at else None
        }

    decision = db.query(OfficerDecision).filter(
        OfficerDecision.tender_id == tender_id,
        OfficerDecision.bidder_id == bidder_id
    ).order_by(OfficerDecision.decided_at.desc()).first()

    audits = db.query(AuditLog).filter(
        (AuditLog.entity_id == bidder_id) | (AuditLog.entity_id == tender_id)
    ).order_by(AuditLog.timestamp.desc()).limit(10).all()

    audit_items = []
    for a in audits:
        audit_items.append({
            "timestamp": a.timestamp.strftime("%d %b %Y %H:%M:%S UTC"),
            "user": a.user,
            "action": a.action,
            "result": a.result
        })

    return {
        "report_title": "AI-Assisted Bid Compliance Verification Report",
        "tender": {
            "tender_id": tender.tender_id,
            "title": tender.title,
            "department": tender.department,
            "ministry": tender.ministry,
            "estimated_value_inr": tender.estimated_value_inr
        },
        "bidder": {
            "bidder_id": bidder.bidder_id,
            "company_name": bidder.company_name,
            "pan": bidder.pan,
            "gstin": bidder.gstin,
            "cin": bidder.cin,
            "udyam_number": bidder.udyam_number,
            "address": bidder.address,
            "declared_local_content": bidder.declared_local_content
        },
        "verification": ver_data,
        "officer_decision": {
            "decision": decision.decision if decision else "PENDING PROCUREMENT OFFICER",
            "officer_email": decision.officer_email if decision else None,
            "comments": decision.comments if decision else "Evaluation pending officer final review.",
            "decided_at": decision.decided_at.isoformat() if decision else None
        },
        "recent_audit_trail": audit_items,
        "generated_at": datetime.now(timezone.utc).strftime("%d %B %Y, %H:%M:%S UTC"),
        "disclaimer": "This document is generated by BidSentinel AI Decision Support System. Final qualification/disqualification authority rests exclusively with the authorized Procurement Officer."
    }

@router.get("/{tender_id}/{bidder_id}/html", response_class=HTMLResponse)
def get_printable_html_report(
    tender_id: str,
    bidder_id: str,
    db: Session = Depends(get_db)
):
    """
    Renders a print-ready, high-fidelity government-style evaluation dossier.
    """
    data = get_report_data(tender_id, bidder_id, db)
    t = data["tender"]
    b = data["bidder"]
    v = data["verification"]
    d = data["officer_decision"]
    reqs = v.get("requirement_results", [])

    rows_html = ""
    for r in reqs:
        status_color = "#16a34a" if r.get("status") == "COMPLIANT" else ("#ca8a04" if r.get("status") == "REVIEW_REQUIRED" else "#dc2626")
        rows_html += f"""
        <tr>
            <td style="padding: 8px; border: 1px solid #e2e8f0; font-weight: 500;">{r.get('title')}</td>
            <td style="padding: 8px; border: 1px solid #e2e8f0;">{r.get('category')}</td>
            <td style="padding: 8px; border: 1px solid #e2e8f0; color: {status_color}; font-weight: bold;">{r.get('status')}</td>
            <td style="padding: 8px; border: 1px solid #e2e8f0;">{r.get('source')}</td>
            <td style="padding: 8px; border: 1px solid #e2e8f0; font-size: 12px;">{r.get('evidence_summary')}</td>
            <td style="padding: 8px; border: 1px solid #e2e8f0; font-size: 12px; color: #475569;">{r.get('reason')}</td>
        </tr>
        """

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8"/>
        <title>BidSentinel - AI Verification Dossier</title>
        <style>
            body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #0f172a; line-height: 1.5; }}
            .header {{ border-bottom: 2px solid #0f172a; padding-bottom: 15px; margin-bottom: 20px; }}
            .emblem {{ font-size: 18px; font-weight: 700; color: #1e293b; text-transform: uppercase; }}
            .subtitle {{ color: #475569; font-size: 14px; margin-top: 4px; }}
            .badge {{ display: inline-block; padding: 4px 10px; border-radius: 4px; font-weight: bold; font-size: 12px; }}
            .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 20px; }}
            .card {{ border: 1px solid #cbd5e1; border-radius: 6px; padding: 15px; background: #f8fafc; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 15px; font-size: 13px; }}
            th {{ background: #f1f5f9; padding: 10px; border: 1px solid #cbd5e1; text-align: left; }}
            .decision-box {{ margin-top: 25px; padding: 15px; border: 2px solid #0284c7; border-radius: 6px; background: #f0f9ff; }}
            .footer {{ margin-top: 40px; font-size: 11px; color: #64748b; border-top: 1px solid #e2e8f0; padding-top: 10px; }}
            @media print {{
                body {{ margin: 15mm; }}
                .no-print {{ display: none; }}
            }}
        </style>
    </head>
    <body>
        <div class="no-print" style="margin-bottom: 20px;">
            <button onclick="window.print()" style="background: #0284c7; color: white; border: none; padding: 8px 16px; border-radius: 4px; cursor: pointer; font-weight: 600;">
                Print / Save as PDF
            </button>
        </div>

        <div class="header">
            <div class="emblem">Government e-Marketplace (GeM) — Procurement Intelligence</div>
            <h1 style="margin: 6px 0 0 0; font-size: 24px;">AI-Assisted Bid Compliance Verification Report</h1>
            <div class="subtitle">Generated on {data['generated_at']} | Prototype Decision-Support System</div>
        </div>

        <div class="grid">
            <div class="card">
                <h3 style="margin-top:0;">Tender Specifications</h3>
                <p><strong>Tender ID:</strong> {t['tender_id']}</p>
                <p><strong>Title:</strong> {t['title']}</p>
                <p><strong>Department:</strong> {t['department']}</p>
                <p><strong>Estimated Value:</strong> INR {t['estimated_value_inr']:,.2f}</p>
            </div>
            <div class="card">
                <h3 style="margin-top:0;">Bidder Profile</h3>
                <p><strong>Company:</strong> {b['company_name']}</p>
                <p><strong>PAN:</strong> {b['pan']} | <strong>GSTIN:</strong> {b['gstin']}</p>
                <p><strong>CIN:</strong> {b['cin'] or 'N/A'} | <strong>Udyam:</strong> {b['udyam_number'] or 'N/A'}</p>
                <p><strong>Local Content Declared:</strong> {b['declared_local_content']}%</p>
            </div>
        </div>

        <div class="card" style="margin-bottom: 20px; background: #ffffff;">
            <h3 style="margin-top:0;">Evaluation Summary</h3>
            <div style="display: flex; gap: 30px; align-items: center;">
                <div>
                    <span style="font-size: 36px; font-weight: 800; color: #0f172a;">{v['compliance_score']}/100</span>
                    <div style="font-size: 12px; color: #64748b; font-weight: 600;">COMPLIANCE SCORE</div>
                </div>
                <div>
                    <span style="font-size: 20px; font-weight: 700; color: {'#16a34a' if v['risk_level']=='LOW' else ('#ca8a04' if v['risk_level']=='MEDIUM' else '#dc2626')};">
                        {v['risk_level']} RISK
                    </span>
                    <div style="font-size: 12px; color: #64748b; font-weight: 600;">RISK CLASSIFICATION</div>
                </div>
            </div>
            <div style="margin-top: 15px; font-size: 13px;">
                <strong>AI Verification Finding & Advisory:</strong><br/>
                <em>{v['ai_recommendation']}</em>
            </div>
        </div>

        <h3>Requirement Verification Matrix</h3>
        <table>
            <thead>
                <tr>
                    <th>Requirement</th>
                    <th>Category</th>
                    <th>Status</th>
                    <th>Source</th>
                    <th>Evidence Summary</th>
                    <th>Rule Engine Reason</th>
                </tr>
            </thead>
            <tbody>
                {rows_html}
            </tbody>
        </table>

        <div class="decision-box">
            <h3 style="margin-top:0; color: #0369a1;">Procurement Officer Final Determination</h3>
            <p><strong>Officer Decision:</strong> <span style="font-weight: 700;">{d['decision']}</span></p>
            <p><strong>Officer Comments:</strong> {d['comments']}</p>
            <p style="font-size: 12px; color: #64748b;"><strong>Recorded By:</strong> {d['officer_email'] or 'Pending'} | <strong>Timestamp:</strong> {d['decided_at'] or 'Pending'}</p>
        </div>

        <div class="footer">
            {data['disclaimer']}
        </div>
    </body>
    </html>
    """
    return HTMLResponse(content=html)
